title: Git for All

description:
  A quick and short guide to Git aimed primarily at non-developers.  
  Git concepts explained with simple examples and illustrations.  
  No terminal commands.

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://kitswas.github.io" # the base hostname & protocol of the site
# for jekyll-sitemap
